### ISSUE TITLE
Cannot compile `Blocks` because of `OutOfMemoryError`

### ISSUE THREAD

**Issue by SolidBlock-cn** [Vineflower/vineflower#251]
When trying to compile `Blocks` in the IDEA that installed the Quiltflower extension (not running the compileWithQuiltflower gradle task), there is following code:
```java
static {
    // $QF: Couldn't be decompiled
    // Please report this to the Quiltflower issue tracker, at https://github.com/QuiltMC/quiltflower/issues with a copy of the class file (if you have the rights to distribute it!)
    // java.lang.OutOfMemoryError: Java heap space
    //   at java.base/java.util.Arrays.copyOf(Arrays.java:3585)
    //   at org.jetbrains.java.decompiler.util.SFormsFastMapDirect.getCopy(SFormsFastMapDirect.java:72)
    //   at org.jetbrains.java.decompiler.modules.decompiler.sforms.SFormsConstructor.varMapToGraph(SFormsConstructor.java:1017)
    //   at org.jetbrains.java.decompiler.modules.decompiler.sforms.SFormsConstructor.updateVarExprent(SFormsConstructor.java:640)
    //   at org.jetbrains.java.decompiler.modules.decompiler.sforms.SFormsConstructor.processExprent(SFormsConstructor.java:274)
    //   at org.jetbrains.java.decompiler.modules.decompiler.sforms.SFormsConstructor.ssaStatements(SFormsConstructor.java:202)
    //   at org.jetbrains.java.decompiler.modules.decompiler.sforms.SFormsConstructor.splitVariables(SFormsConstructor.java:165)
    //   at org.jetbrains.java.decompiler.modules.decompiler.StackVarsProcessor.simplifyStackVars(StackVarsProcessor.java:57)
    //   at org.jetbrains.java.decompiler.main.rels.MethodProcessor.codeToJava(MethodProcessor.java:201)
    //
    // Bytecode:
    // 0000: ldc_w "air"
    // 0003: new net/minecraft/block/AirBlock
    // 0006: dup
...
```

**Comment by Kroppeb** [comment]
Isn't this also an issue with the standard fernflower?

**Comment by SolidBlock-cn** [comment]
Fernflower does not have this issue. If I run `genSourcesWithQuiltflower` gradle task, the issue does not happen as well.

**Comment by Kroppeb** [comment]
My bad, I somehow got it confused with `org.bukkit.Material`
