### ISSUE TITLE
Couldn't be decompiled: NPE `this.varVersions` is null

### ISSUE THREAD

**Issue by 9999years** [Vineflower/vineflower#323]
```
// $VF: Couldn't be decompiled
// Please report this to the Vineflower issue tracker, at https://github.com/Vineflower/vineflower/issues with a copy of the class file (if you have the rights to distribute it!)
// java.lang.NullPointerException: Cannot invoke "org.jetbrains.java.decompiler.modules.decompiler.vars.VarVersionsProcessor.setVarFinal(org.jetbrains.java.decompiler.modules.decompiler.vars.VarVersionPair, org.jetbrains.java.decompiler.modules.decompiler.vars.VarTypeProcessor$FinalType)" because "this.varVersions" is null
//   at org.jetbrains.java.decompiler.modules.decompiler.vars.VarProcessor.setVarFinal(VarProcessor.java:183)
//   at org.jetbrains.java.decompiler.main.rels.NestedClassProcessor.insertLocalVars(NestedClassProcessor.java:653)
//   at org.jetbrains.java.decompiler.main.rels.NestedClassProcessor.processClass(NestedClassProcessor.java:89)
//   at org.jetbrains.java.decompiler.main.ClassesProcessor.processClass(ClassesProcessor.java:424)
//   at org.jetbrains.java.decompiler.main.Fernflower.processClass(Fernflower.java:174)
//   at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$2(ContextUnit.java:155)
```

**Comment by jaskarth** [comment]
Hi,
What Vineflower version are you using, and do you have the rights to share the class that is being decompiled here?

**Comment by jaskarth** [comment]
Closing for lack of information. If you have additional details, please feel free to reopen this issue.
