### ISSUE TITLE
doesnt work 

### ISSUE THREAD

**Issue by kittenvr** [Vineflower/vineflower#385]
## Vineflower version

vineflower-1.10.1
## Describe the bug
gives errors in terminal

## Additional information
java -jar vineflower-1.10.1.jar navine-3.2.8.jar src

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/jetbrains/java/decompiler/main/decompiler/ConsoleDecompiler has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:621)

**Comment by Geolykt** [comment]
Ensure that you are using the right version of Java. I believe the 1.10 releases use Java 11.
You seem to be using Java 8, which of course won't work.

if absolutely necessary, you could try out tools such as JavaDowngrader (https://github.com/RaphiMC/JavaDowngrader)

**Comment by jaskarth** [comment]
Yes, Vineflower 1.9+ requires Java 11 or higher, while you have Java 8 installed.

**Comment by kittenvr** [comment]
> Ensure that you are using the right version of Java. I believe the 1.10 releases use Java 11. You seem to be using Java 8, which of course won't work.
> 
> if absolutely necessary, you could try out tools such as JavaDowngrader (https://github.com/RaphiMC/JavaDowngrader)

how do  i switch java i have installed 11, 17, 18, 21

**Comment by Geolykt** [comment]
This is an issue tracker, not a help forum.
Otherwise: On linux: using the alternatives command or similar. On other plattforms: I do not know
