### ISSUE TITLE
InitializerProcessor NPE 

### ISSUE THREAD

**Issue by InventivetalentDev** [Vineflower/vineflower#400]
## Vineflower version
1.10.0/1.10.1/1.11.0

## Describe the bug
Failing to properly decompile most classes of the latest MC snapshots 24w21a and 24w21b.
Worked without issues on 24w20a.

Most classes just contain that stacktrace, but a couple start with properly decompiled code and then fail halfway through. 

## Additional information
(same stacktrace for all failed classes as far as I can tell)
```
// $VF: Couldn't be decompiled
// Please report this to the Vineflower issue tracker, at https://github.com/Vineflower/vineflower/issues with a copy of the class file (if you have the rights to distribute it!)
// java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "varName" is null
//   at org.jetbrains.java.decompiler.main.InitializerProcessor.isExprentIndependent(InitializerProcessor.java:423)
//   at org.jetbrains.java.decompiler.main.InitializerProcessor.extractDynamicInitializers(InitializerProcessor.java:335)
//   at org.jetbrains.java.decompiler.main.InitializerProcessor.extractInitializers(InitializerProcessor.java:44)
//   at org.jetbrains.java.decompiler.main.ClassWriter.invokeProcessors(ClassWriter.java:97)
//   at org.jetbrains.java.decompiler.main.ClassWriter.writeClass(ClassWriter.java:348)
//   at org.jetbrains.java.decompiler.main.ClassesProcessor.writeClass(ClassesProcessor.java:474)
//   at org.jetbrains.java.decompiler.main.Fernflower.getClassContent(Fernflower.java:191)
//   at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$3(ContextUnit.java:187)
```

```
WARN:  Class BookSlotModelCacheKey couldn't be written.
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "varName" is null
        at org.jetbrains.java.decompiler.main.InitializerProcessor.isExprentIndependent(InitializerProcessor.java:423)
        at org.jetbrains.java.decompiler.main.InitializerProcessor.extractDynamicInitializers(InitializerProcessor.java:335)
        at org.jetbrains.java.decompiler.main.InitializerProcessor.extractInitializers(InitializerProcessor.java:44)
        at org.jetbrains.java.decompiler.main.ClassWriter.invokeProcessors(ClassWriter.java:97)
        at org.jetbrains.java.decompiler.main.ClassWriter.writeClass(ClassWriter.java:348)
        at org.jetbrains.java.decompiler.main.ClassWriter.writeClass(ClassWriter.java:492)
        at org.jetbrains.java.decompiler.main.ClassesProcessor.writeClass(ClassesProcessor.java:474)
        at org.jetbrains.java.decompiler.main.Fernflower.getClassContent(Fernflower.java:191)
        at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$3(ContextUnit.java:187)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by MiniDigger** [comment]
Working fine here on some slightly outdated 1.11 snapshot, consider trying 1.10.1 too

**Comment by InventivetalentDev** [comment]
@MiniDigger I tried again with 1.10.1 and 1.11.0 and I'm getting the same exception 🤔 
```
// $VF: Couldn't be decompiled
// Please report this to the Vineflower issue tracker, at https://github.com/Vineflower/vineflower/issues with a copy of the class file (if you have the rights to distribute it!)
// java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "varName" is null
//   at org.jetbrains.java.decompiler.main.InitializerProcessor.isExprentIndependent(InitializerProcessor.java:423)
//   at org.jetbrains.java.decompiler.main.InitializerProcessor.extractDynamicInitializers(InitializerProcessor.java:335)
//   at org.jetbrains.java.decompiler.main.InitializerProcessor.extractInitializers(InitializerProcessor.java:44)
//   at org.jetbrains.java.decompiler.main.ClassWriter.invokeProcessors(ClassWriter.java:98)
//   at org.jetbrains.java.decompiler.main.ClassWriter.writeClass(ClassWriter.java:352)
//   at org.jetbrains.java.decompiler.main.ClassesProcessor.writeClass(ClassesProcessor.java:485)
//   at org.jetbrains.java.decompiler.main.Fernflower.getClassContent(Fernflower.java:191)
//   at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$3(ContextUnit.java:192)
```

**Comment by MiniDigger** [comment]
what arguments do you use? 
for reference, we use: https://github.com/PaperMC/sculptor/blob/main/sculptor-shared/src/main/kotlin/io/papermc/sculptor/shared/MacheExtension.kt#L71 on `1.11.0-20240522.034251-27` for 24w21b right now and it decompiler properly both locally and in CI

**Comment by InventivetalentDev** [comment]
@MiniDigger https://github.com/InventivetalentDev/DecompilerMC/blob/90a0e25cb74c64114ba5c7da72f086f1acd67ddd/main.py#L260-L272 
switching those out for the sculptor args didn't help either

**Comment by InventivetalentDev** [comment]
I got things working with sculptor/mache, so I guess there's _something_ weird in my setup that suddenly broke with the new snapshots

**Comment by MiniDigger** [comment]
worth noting is that mache/sculptor has a preprocessor step using codebook, maybe that is fixing it for us, I think neoforge also does some preprocessing.
didnt have time to test using a vanilla jar yet.

**Comment by mat-1** [comment]
I have the same issue. Adding a `varName == null ||` to [the line where it's erroring](https://github.com/Vineflower/vineflower/blob/ddf84710f8521ce62d1e3e55a39d300432d6b729/src/org/jetbrains/java/decompiler/main/InitializerProcessor.java#L423) appears to fix it, but this probably isn't the best solution.

**Comment by jaskarth** [comment]
Yeah, it's possible for the method to return null but there's no null check. I think that's an error, we should really be adding the null check.
