### ISSUE TITLE
IOOBE in `getInferredExprType`

### ISSUE THREAD

**Issue by Gaming32** [Vineflower/vineflower#410]
## Vineflower version

1.10.1

## Describe the bug

When I try to decompile this class file I created, an IIOBE occurs in `getInferredExprType` while decompiling the main method.

## Additional information

<details>
<summary>Vineflower decompilation and error</summary>

```java
package io.github.gaming32.reifiedjava;

import java.lang.invoke.MethodHandle;

public class TestConsumer {
   public static <T extends Comparable<T>> void consumer(Class<T> var0, MethodHandle var1, T var2) {
      System.out.println(var2 + " <=> 0: " + var2.compareTo((Comparable)var1.invokeExact((int)0)));
   }

   public static void main(String[] args) {
      // $VF: Couldn't be decompiled
      // Please report this to the Vineflower issue tracker, at https://github.com/Vineflower/vineflower/issues with a copy of the class file (if you have the rights to distribute it!)
      // java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
      //   at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
      //   at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
      //   at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
      //   at java.base/java.util.Objects.checkIndex(Objects.java:365)
      //   at java.base/java.util.ArrayList.get(ArrayList.java:428)
      //   at org.jetbrains.java.decompiler.modules.decompiler.exps.NewExprent.getInferredExprType(NewExprent.java:183)
      //   at org.jetbrains.java.decompiler.modules.decompiler.exps.InvocationExprent.getInferredExprType(InvocationExprent.java:503)
      //   at org.jetbrains.java.decompiler.modules.decompiler.ExprProcessor.listToJava(ExprProcessor.java:893)
      //   at org.jetbrains.java.decompiler.modules.decompiler.stats.BasicBlockStatement.toJava(BasicBlockStatement.java:90)
      //   at org.jetbrains.java.decompiler.modules.decompiler.stats.RootStatement.toJava(RootStatement.java:36)
      //   at org.jetbrains.java.decompiler.main.ClassWriter.writeMethod(ClassWriter.java:1283)
      //
      // Bytecode:
      // 00: bipush -5
      // 02: bipush 5
      // 03: invokestatic java/util/stream/IntStream.rangeClosed (II)Ljava/util/stream/IntStream;
      // 06: invokeinterface java/util/stream/IntStream.boxed ()Ljava/util/stream/Stream; 1
      // 0b: ldc java/lang/Integer
      // 0d: ldc _ Ljava/lang/invoke/MethodHandle; bsm=java/lang/invoke/ConstantBootstraps.invoke (Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/Class;Ljava/lang/invoke/MethodHandle;[Ljava/lang/Object;)Ljava/lang/Object; args=[ java/lang/invoke/MethodHandle.asType (Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/MethodHandle;, java/lang/Integer.<init> (I)V, (I)Ljava/lang/Comparable; ]
      // 0f: invokedynamic accept (Ljava/lang/Class;Ljava/lang/invoke/MethodHandle;)Ljava/util/function/Consumer; bsm=java/lang/invoke/LambdaMetafactory.metafactory (Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; args=[ (Ljava/lang/Object;)V, io/github/gaming32/reifiedjava/TestConsumer.consumer (Ljava/lang/Class;Ljava/lang/invoke/MethodHandle;Ljava/lang/Comparable;)V, (Ljava/lang/Integer;)V ]
      // 14: invokeinterface java/util/stream/Stream.forEach (Ljava/util/function/Consumer;)V 2
      // 19: return
   }
}
```
</details>

<details>
<summary>CFR decompilation</summary>

```java
/*
 * Decompiled with CFR 0.152.
 */
package io.github.gaming32.reifiedjava;

import java.lang.invoke.ConstantBootstraps;
import java.lang.invoke.MethodHandle;
import java.util.stream.IntStream;
/*
 * Uses jvm11+ dynamic constants - pseudocode provided - see https://www.benf.org/other/cfr/dynamic-constants.html
 */
public class TestConsumer {
    public static <T extends Comparable<T>> void consumer(Class<T> clazz, MethodHandle methodHandle, T comparable) {
        System.out.println(comparable + " <=> 0: " + comparable.compareTo((Comparable)methodHandle.invokeExact(0)));
    }

    public static void main(String[] args) {
        IntStream.rangeClosed(-5, 5).boxed().forEach(arg_0 -> TestConsumer.consumer(Integer.class, (MethodHandle)( /* dynamic constant */ (Object)ConstantBootstraps.invoke("_", new Object[]{asType(java.lang.invoke.MethodType ), <init>(int ), (I)Ljava/lang/Comparable;})), arg_0));
    }
}
```
</details>

<details>
<summary>Original source, compiled manually</summary>

```java
package io.github.gaming32.reifiedjava;

import java.util.stream.IntStream;

public class TestConsumer {
    public static <reified T extends Comparable<T> & new(int)> void consumer(T obj) {
        System.out.println(obj + " <=> 0: " + obj.compareTo(new T(0)));
    }

    public static void main(String[] args) {
        IntStream.rangeClosed(-5, 5)
            .boxed()
            .forEach(TestConsumer::consumer);
    }
}
```
</details>

[Source, class file, and generator](https://github.com/user-attachments/files/16503318/TestConsumer.zip) (Java 21 required to run class file, Java 22 Preview required to run generator)

**Comment by jaskarth** [comment]
Should be fixed with [e08520b](https://github.com/Vineflower/vineflower/commit/e08520bea35458256d2220bc2119795f39475f35). Thanks for the report!
