### ISSUE TITLE
NPE for several minecraft class decompilation

### ISSUE THREAD

**Issue by Machine-Maker** [Vineflower/vineflower#421]
## Vineflower version
cb905ac48d948007e76f16234adcb94c280369ad

## Describe the bug
Bunch of classes in the Minecraft source throw NPEs when decompiling after https://github.com/Vineflower/vineflower/pull/378. One such stacktrace is below for StreamCodec.java
```
// $VF: Couldn't be decompiled
// Please report this to the Vineflower issue tracker, at https://github.com/Vineflower/vineflower/issues with a copy of the class file (if you have the rights to distribute it!)
// java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "org.jetbrains.java.decompiler.modules.decompiler.vars.VarProcessor.getVarName(org.jetbrains.java.decompiler.modules.decompiler.vars.VarVersionPair)" is null
//   at org.jetbrains.java.decompiler.modules.decompiler.vars.VarDefinitionHelper.iterateClashingExprent(VarDefinitionHelper.java:1659)
//   at org.jetbrains.java.decompiler.modules.decompiler.vars.VarDefinitionHelper.iterateClashingNames(VarDefinitionHelper.java:1491)
//   at org.jetbrains.java.decompiler.modules.decompiler.vars.VarDefinitionHelper.iterateClashingNames(VarDefinitionHelper.java:1540)
//   at org.jetbrains.java.decompiler.modules.decompiler.vars.VarDefinitionHelper.remapClashingNames(VarDefinitionHelper.java:1454)
//   at org.jetbrains.java.decompiler.modules.decompiler.vars.VarProcessor.rerunClashing(VarProcessor.java:99)
//   at org.jetbrains.java.decompiler.main.ClassWriter.invokeProcessors(ClassWriter.java:118)
//   at org.jetbrains.java.decompiler.main.ClassWriter.writeClass(ClassWriter.java:352)
//   at org.jetbrains.java.decompiler.main.ClassesProcessor.writeClass(ClassesProcessor.java:500)
//   at org.jetbrains.java.decompiler.main.Fernflower.getClassContent(Fernflower.java:191)
//   at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$3(ContextUnit.java:194)
```

## Additional information
If I try to fix the NPE by changing the object.equals(other), to an Objects.equal(), I get new issues, not stacktraces, but an increase in decompile errors. Its possible the best solution is to just revert that commit entirely. 

![image](https://github.com/user-attachments/assets/dc33ff89-b356-47f9-9f41-b3929b47cfb0)

**Comment by jaskarth** [comment]
This was fixed in c45692ca02d8181b4561cafe631408d5ca093b04. Thanks for the report!
