### ISSUE TITLE
[kotlin] NullPointerException when accessing annotations in KProperty.stringify

### ISSUE THREAD

**Issue by xhyrom** [Vineflower/vineflower#422]
## Vineflower version
[https://github.com/Vineflower/vineflower/commit/fdf1a36aa32b3d3619910dbac775c30797a843a2](https://github.com/Vineflower/vineflower/commit/fdf1a36aa32b3d3619910dbac775c30797a843a2) 

## Describe the bug
Unable to decompile class because missing annotations

## Additional information
```java
java.lang.NullPointerException: Cannot invoke "org.jetbrains.java.decompiler.struct.attr.StructAnnotationAttribute.getAnnotations()" because "this.annotations" is null
  at org.vineflower.kotlin.struct.KProperty.stringify(KProperty.java:53)
  at org.vineflower.kotlin.KotlinWriter.writeClass(KotlinWriter.java:392)
  at org.jetbrains.java.decompiler.main.ClassesProcessor.writeClass(ClassesProcessor.java:500)
  at org.jetbrains.java.decompiler.main.Fernflower.getClassContent(Fernflower.java:196)
  at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$3(ContextUnit.java:194)
```

**Comment by sschr15** [comment]
This should be fixed in https://github.com/Vineflower/vineflower/commit/34a6163e926f344b4d69835a4025650c966da4e3
