### ISSUE TITLE
[kotlin] StackOverflowError with lambdas

### ISSUE THREAD

**Issue by xhyrom** [Vineflower/vineflower#424]
## Vineflower version
vineflower-1.11.0-20240823.162115-41

## Additional information
```kt
internal fun setBroadcastThumbnailParams(width: Int, height: Int, intervalSeconds: Int, callback: (String) -> Unit) {
      r.h(var4, "callback");
      if (this.screenCapturer != null) {
         this.screenCapturer
            .component1()
            .setThumbnailEmitter(
               new ThumbnailEmitter(
                  var1,
                  var2,
                  (long)var3 * 1000L,
                  new Function1<Bitmap, Unit>(this, var4)// $VF: Couldn't be decompiled
         // Please report this to the Vineflower issue tracker, at https://github.com/Vineflower/vineflower/issues with a copy of the class file (if you have the rights to distribute it!)
         // java.lang.StackOverflowError
         //   at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
         //   at org.jetbrains.java.decompiler.modules.decompiler.vars.VarDefinitionHelper.iterateClashingExprent(VarDefinitionHelper.java:1634)
         //   at org.jetbrains.java.decompiler.modules.decompiler.vars.VarDefinitionHelper.iterateClashingNames(VarDefinitionHelper.java:1492)
         //   at org.jetbrains.java.decompiler.modules.decompiler.vars.VarDefinitionHelper.iterateClashingNames(VarDefinitionHelper.java:1541)
         //   at org.jetbrains.java.decompiler.modules.decompiler.vars.VarDefinitionHelper.iterateClashingExprent(VarDefinitionHelper.java:1672)
         //   at org.jetbrains.java.decompiler.modules.decompiler.vars.VarDefinitionHelper.iterateClashingNames(VarDefinitionHelper.java:1492)
```

**Comment by jaskarth** [comment]
This has been fixed in the latest dev version. Thanks for the bug report!
