### ISSUE TITLE
[kotlin] couldn't find method 

### ISSUE THREAD

**Issue by xhyrom** [Vineflower/vineflower#425]
## Vineflower version
vineflower-1.11.0-20240823.162115-41

## Additional information
```
/*
$VF: Unable to decompile class
Please report this to the Vineflower issue tracker, at https://github.com/Vineflower/vineflower/issues with a copy of the class file (if you have the rights to distribute it!)
java.lang.IllegalStateException: Couldn't find method downloadSingleFile (Ljava/lang/String;Ljava/util/List;Ljava/lang/String;Lcom/discord/bundle_updater/BundleUpdater$Patch;Ljava/io/File;I)Leh/r; in class com/discord/bundle_updater/BundleUpdater
  at org.vineflower.kotlin.struct.KFunction.parse(KFunction.java:154)
  at org.vineflower.kotlin.KotlinWriter.writeClass(KotlinWriter.java:223)
  at org.jetbrains.java.decompiler.main.ClassesProcessor.writeClass(ClassesProcessor.java:474)
  at org.jetbrains.java.decompiler.main.Fernflower.getClassContent(Fernflower.java:191)
  at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$3(ContextUnit.java:187)
*/
```

**Comment by jaskarth** [comment]
Thanks a lot for this issue! It's likely to have been fixed with the recent Kotlin changes, but if it persists please re-open this ticket.
