### ISSUE TITLE
Couldn't be decompiled: Cannot invoke "org.jetbrains.java.decompiler.struct.StructMethod.isSynthetic()" 

### ISSUE THREAD

**Issue by JuraSciix** [Vineflower/vineflower#434]
## Vineflower version
1.10.1

## Describe the bug
The code generated by vineflower:
```java
package litebans;// $VF: Couldn't be decompiled
// Please report this to the Vineflower issue tracker, at https://github.com/Vineflower/vineflower/issues with a copy of the class file (if you have the rights to distribute it!)
// java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "org.jetbrains.java.decompiler.struct.StructMethod.isSynthetic()" because "mt" is null
//   at org.jetbrains.java.decompiler.main.ClassesProcessor.processClass(ClassesProcessor.java:439)
//   at org.jetbrains.java.decompiler.main.Fernflower.processClass(Fernflower.java:183)
//   at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$2(ContextUnit.java:164)
// Caused by: java.lang.NullPointerException: Cannot invoke "org.jetbrains.java.decompiler.struct.StructMethod.isSynthetic()" because "mt" is null
//   at org.jetbrains.java.decompiler.main.ClassesProcessor$ClassNode.<init>(ClassesProcessor.java:623)
//   at org.jetbrains.java.decompiler.main.rels.LambdaProcessor.processClass(LambdaProcessor.java:89)
//   at org.jetbrains.java.decompiler.main.ClassesProcessor.processClass(ClassesProcessor.java:419)
//   at org.jetbrains.java.decompiler.main.Fernflower.processClass(Fernflower.java:183)
//   at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$2(ContextUnit.java:164)
```

## Additional information
Class file archived to ZIP:
[VelocityPlugin.zip](https://github.com/user-attachments/files/17185507/VelocityPlugin.zip)

**Comment by jaskarth** [comment]
Hi, it doesn't seem like you have the right to redistribute the classes you linked in the issue, so I have to delete it. Regardless, it seems this issue is fixed in the dev version for 1.11.
