### ISSUE TITLE
 $VF: Couldn't be decompiled

### ISSUE THREAD

**Issue by meiMingle** [Vineflower/vineflower#435]
## Vineflower version
1.10.1

## Describe the bug

> // $VF: Couldn't be decompiled
// Please report this to the Vineflower issue tracker, at https://github.com/Vineflower/vineflower/issues with a copy of the class file (if you have the rights to distribute it!)
// java.lang.RuntimeException: java.util.ConcurrentModificationException
//   at org.jetbrains.java.decompiler.main.ClassesProcessor.processClass(ClassesProcessor.java:439)
//   at org.jetbrains.java.decompiler.main.Fernflower.processClass(Fernflower.java:183)
//   at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$2(ContextUnit.java:164)
// Caused by: java.util.ConcurrentModificationException
//   at java.base/java.util.ArrayList.sort(ArrayList.java:1807)
//   at java.base/java.util.Collections.sort(Collections.java:145)
//   at org.jetbrains.java.decompiler.main.rels.LambdaProcessor.processClass(LambdaProcessor.java:110)
//   at org.jetbrains.java.decompiler.main.ClassesProcessor.processClass(ClassesProcessor.java:419)
//   at org.jetbrains.java.decompiler.main.Fernflower.processClass(Fernflower.java:183)
//   at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$2(ContextUnit.java:164)

## Additional information
[LongFastFixedSetFactory$LongFastFixedSet.zip](https://github.com/user-attachments/files/17504682/LongFastFixedSetFactory.LongFastFixedSet.zip)

**Comment by jaskarth** [comment]
Hi, I tried replicating the bug but I couldn't reproduce the error. Did you decompile the class separately or as part of a larger jar?

**Comment by jaskarth** [comment]
Closing. Please re-open if there are any additional details.
