### ISSUE TITLE
Couldn't Decompile

### ISSUE THREAD

**Issue by AnnoyedUser420** [Vineflower/vineflower#439]
## Vineflower version
Unknown, whatever Enigma 2.5.1 is shipped with.

## Describe the bug
Unable to decompile certain parts of the code.

## Additional information
                // $VF: Couldn't be decompiled
		// Please report this to the Vineflower issue tracker, at https://github.com/Vineflower/vineflower/issues with a copy of the class file (if you have the rights to distribute it!)
		// java.lang.ClassCastException: class org.jetbrains.java.decompiler.modules.decompiler.exps.ConstExprent cannot be cast to class org.jetbrains.java.decompiler.modules.decompiler.exps.InvocationExprent (org.jetbrains.java.decompiler.modules.decompiler.exps.ConstExprent and org.jetbrains.java.decompiler.modules.decompiler.exps.InvocationExprent are in unnamed module of loader 'app')
		//   at org.jetbrains.java.decompiler.modules.decompiler.SwitchHelper.lambda$simplify$0(SwitchHelper.java:94)
		//   at org.jetbrains.java.decompiler.modules.decompiler.flow.DirectGraph.iterateExprents(DirectGraph.java:107)
		//   at org.jetbrains.java.decompiler.modules.decompiler.SwitchHelper.simplify(SwitchHelper.java:71)
		//   at org.jetbrains.java.decompiler.modules.decompiler.SwitchHelper.simplifySwitches(SwitchHelper.java:30)
		//   at org.jetbrains.java.decompiler.modules.decompiler.SwitchHelper.simplifySwitches(SwitchHelper.java:34)
		//   at org.jetbrains.java.decompiler.modules.decompiler.SwitchHelper.simplifySwitches(SwitchHelper.java:34)
		//   at org.jetbrains.java.decompiler.modules.decompiler.SwitchHelper.simplifySwitches(SwitchHelper.java:34)
		//   at org.jetbrains.java.decompiler.modules.decompiler.SwitchHelper.simplifySwitches(SwitchHelper.java:34)
		//   at org.jetbrains.java.decompiler.modules.decompiler.SwitchHelper.simplifySwitches(SwitchHelper.java:34)
		//   at org.jetbrains.java.decompiler.main.rels.MethodProcessor.codeToJava(MethodProcessor.java:376)

**Comment by ix0rai** [comment]
(enigma 2.5.1 ships with VF 1.10.1)

**Comment by MiniDigger** [comment]
it would help to know what part, lol

**Comment by AnnoyedUser420** [comment]
> (enigma 2.5.1 ships with VF 1.10.1)
Is that an old issue?
Why am I being downvoted? Is it because I didn't distribute the class file that I don't have permission to distribute?

**Comment by Earthcomputer** [comment]
You could say the name of the class it was

**Comment by AnnoyedUser420** [comment]
A very, very heavily modified Minecraft.class for a mod that is in private testing. (Based on Infdev 0630-1)

**Comment by mudkipdev** [comment]
Are you decompiling infdev+?

**Comment by AnnoyedUser420** [comment]
> Are you decompiling infdev+?

perhaps, but not strictly decompiling, mapping.

**Comment by jaskarth** [comment]
This issue has been fixed in the latest 1.11.0 branch. Thanks for the report!
